

instal:
	g++ -fPIC model.cpp file_parser.cpp -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGLWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtOpenGL -lQt6OpenGLWidgets -lQt6Widgets -lQt6Core -lOpenGL -lQt6Gui -lQt6OpenGL